{% set name = "sgqlc" %}
{% set version = "17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4febd6d00f001c0fe0dd571e27d87e6d5ae071e8d1f61c66fa772449910953fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sgqlc-codegen = sgqlc.codegen:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - graphql-core >=3.1.7
    - requests
    - websocket-client

test:
  imports:
    - sgqlc
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - sgqlc-codegen --help

about:
  home: https://sgqlc.readthedocs.io/
  license: ISC
  license_file: LICENSE
  summary: Simple GraphQL Client
  dev_url: https://github.com/profusion/sgqlc

extra:
  recipe-maintainers:
    - hoechenberger
